# Generated by Django 5.1.6 on 2025-07-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0004_delete_sharerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('share_date', models.DateField()),
                ('share_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_share_maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('received_invoice_pdf', models.TextField(blank=True, null=True)),
                ('share_duration_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_record', to='transactions.transaction')),
            ],
        ),
    ]
