# Generated by Django 5.1.6 on 2025-07-24 09:06

import django.db.models.deletion
import shares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('project_name', models.CharField(default='KKM', max_length=255)),
                ('share_date', models.DateField(default=shares.models.default_share_date)),
                ('share_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_share_maturity_date', models.DateField(default=shares.models.default_maturity_date)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('share_duration_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_record', to='transactions.transaction')),
            ],
        ),
    ]
