# Generated by Django 5.1.6 on 2025-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerecord',
            name='profit_payout_created',
            field=models.BooleanField(default=False),
        ),
    ]
