# Generated by Django 5.1.6 on 2025-08-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerecord',
            name='received_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_record', to='transactions.transaction'),
        ),
    ]
