# Generated by Django 5.1.6 on 2025-07-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('ic_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('finance', 'Finance'), ('manager', 'Manager')], max_length=20)),
                ('position', models.CharField(choices=[('director', 'Director'), ('officer', 'Officer'), ('auditor', 'Auditor')], max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
