# Generated by Django 5.1.6 on 2025-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('share', 'Share'), ('payment', 'Payment'), ('cancellation', 'Cancellation')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=250.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('ewallet', 'E-Wallet')], default='bank_transfer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
