# Generated by Django 5.1.6 on 2025-08-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('source_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('share', 'Share'), ('payment', 'Payment'), ('cancellation', 'Cancellation'), ('registration_payments', 'Registration Payment')], max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('reinvest', 'Reinvest')], default='in', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=250.0, max_digits=12)),
                ('received_invoice_doc', models.FileField(blank=True, null=True, upload_to='received_invoice_doc/')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('ewallet', 'E-Wallet')], default='bank_transfer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='members.member')),
            ],
        ),
    ]
