# Generated by Django 5.1.6 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('share', 'Share'), ('payment', 'Payment'), ('cancellation', 'Cancellation'), ('registration_payments', 'Registration Payment')], max_length=50),
        ),
    ]
