# Generated by Django 5.1.6 on 2025-07-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project_name', models.CharField(max_length=255)),
                ('share_date', models.DateField()),
                ('share_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_share_maturity_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('received_invoice_pdf', models.TextField(blank=True, null=True)),
                ('share_duration_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_records', to='transactions.transaction')),
            ],
        ),
    ]
