# Generated by Django 5.1.6 on 2025-07-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_sharerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerecord',
            name='share_amount',
        ),
    ]
