# Generated by Django 5.1.6 on 2025-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='received_invoice_doc',
            field=models.FileField(blank=True, null=True, upload_to='received_invoice_doc/'),
        ),
    ]
