# Generated by Django 5.1.6 on 2025-07-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_sharerecord_share_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareRecord',
        ),
    ]
