# Generated by Django 5.1.6 on 2025-08-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitPayout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('payout_type', models.CharField(choices=[('pending', 'Pending'), ('full_transfer', 'Full Transfer'), ('partial', 'Partial Transfer'), ('reinvest', 'Reinvest All')], default='pending', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reinvestment_created', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_payouts', to='members.member')),
            ],
        ),
    ]
