# Generated by Django 5.1.6 on 2025-07-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitPayout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('payout_type', models.CharField(choices=[('full_transfer', 'Full Transfer'), ('partial', 'Partial Transfer'), ('reinvest', 'Reinvest All')], max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharerecord')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
