# Generated by Django 5.1.6 on 2025-07-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0001_initial'),
        ('shares', '0002_sharerecord_profit_payout_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitpayout',
            name='reinvestment_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profitpayout',
            name='share_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shares.sharerecord'),
        ),
    ]
