# Generated by Django 5.1.6 on 2025-08-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profits', '0001_initial'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitpayout',
            name='share_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shares.sharerecord'),
        ),
    ]
