# Generated by Django 5.1.6 on 2025-07-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_alter_transaction_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('payment_code', models.CharField(blank=True, max_length=30, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payment', to='transactions.transaction')),
            ],
        ),
    ]
