# Generated by Django 5.1.6 on 2025-08-07 20:10

import django.db.models.deletion
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_code', models.CharField(blank=True, max_length=30, null=True)),
                ('confirmed_at', models.DateTimeField(default=registrations.models.default_share_date)),
                ('created_at', models.DateTimeField(default=registrations.models.default_share_date)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='members.member')),
            ],
        ),
    ]
