# Generated by Django 5.1.6 on 2025-07-24 10:13

import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpayment',
            name='confirmed_at',
            field=models.DateTimeField(default=registrations.models.default_share_date),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='created_at',
            field=models.DateTimeField(default=registrations.models.default_share_date),
        ),
    ]
