# Generated by Django 5.1.6 on 2025-07-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('cancellation_date', models.DateField(auto_now_add=True)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('penalty_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.sharerecord')),
            ],
        ),
    ]
