# Generated by Django 5.1.6 on 2025-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrecord',
            name='payout_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('full_transfer', 'Full Transfer')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
