# Generated by Django 5.1.6 on 2025-07-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancels', '0003_alter_cancellationrecord_penalty_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrecord',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
