# Generated by Django 5.1.6 on 2025-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancels', '0007_alter_cancellationrecord_penalty_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrecord',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
