# Generated by Django 5.1.6 on 2025-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_alter_administrator_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator')], default='admin', max_length=20),
        ),
    ]
