# Generated by Django 5.1.6 on 2025-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_alter_administrator_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
