# Generated by Django 5.1.6 on 2025-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0007_alter_administrator_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
