# Generated by Django 5.1.6 on 2025-07-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
